name: Waka Readme

on:
  schedule:
    - cron: "55 12,20-23 * * *"

jobs:
  # This workflow contains a single job called "build"
  update-wakatime:
    name: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⚪⚫
