name: Waka Readme

on:
  push:
    branches: [ main ]
  schedule:
#    - cron: "55 12,20-23 * * *"
#    - cron: "5 3,12-14 * * *"  
#    - cron: "8 * * * *"  
#    - cron: "0 17-20 * * *"
    - cron: "0 0-3 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  update-wakatime:
    name: 测试中文
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: shuxuecode/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⚪⚫
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.0.0-rc.2
