name: Waka Readme

on:
  push:
    branches: [ main ]
  schedule:
#    - cron: "55 12,20-23 * * *"
#    - cron: "5 3,12-14 * * *"  
#    - cron: "8 * * * *"  
#    - cron: "0 17-20 * * *"
    - cron: "0 0-3 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  update-wakatime:
    name: 测试中文
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: shuxuecode/waka-readme@master
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      #     BLOCKS: ⚪⚫

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.0.0-rc.2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with: 
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0